config/routes.rb
Rails.application.routes.draw do




  root to: 'public/homes#top'

  devise_for :admins, controllers: {
   sessions: 'admin/admins/sessions',
   passwords: 'admin/admins/passwords'
  }

  namespace :admin do
   #resources :customers, only: %i(show edit update index)
  # resources :questions, only: %i(index destroy)
  end
  devise_for :customers, controllers: {
    sessions:      'public/customers/sessions',
    passwords:     'public/customers/passwords',
    registrations: 'public/customers/registrations'
  }


  scope module: :public do
    get 'orders/thank_you' => 'orders#thank_you'
    get 'orders/confirm' => 'orders#new'
    resources :orders ,only: [:new ,:index ,:show ,:create] do
      collection do
        post :confirm
      end
    end

    resources :customers ,only: [:show,:edit,:update]
    resources :deliveries ,only: [:index, :create, :edit, :destroy, :update]
    resources :products ,only: [ :index, :show]

    get 'search' => 'products#search'
    delete '/cart_items/destroy_all'
    resources :cart_items ,only: [:index, :create, :update, :destroy]

    get '/' => 'homes#top', as: 'homes_top'
    get 'homes/about'
    get 'customers/:id/confirm' => 'customers#confirm', as: 'customers_confirm'
    patch 'customers/destroy/:id' => 'customers#destroy' , as: 'customers_destroy'
    get 'public/search' => 'searches#search', as: 'public_search'
  end


  namespace :admin do
    get '/customer/order/:id' => 'orders#customerindex',as: 'customer_orders'
    resources :orders ,only: [:show,:index,:update]
    resources :order_details ,only: [:update]
    resources :customers ,only: [:index, :show, :edit, :update]
    resources :genres ,only: [:index, :create, :edit, :update, :destroy]
    get "/genres/:id", to: "genres#edit"
    resources :products ,only: [:new, :create, :show, :index, :edit, :update, :destroy]
    root to: 'orders#index'
    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ぁ-んァ-ン]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ぁ-んァ-ン]+\z/}
  validates :postal_code, presence: true, format: {with: /\A\d{3}[-]?\d{4}\z/}
  validates :address, presence: true
  validates :telephone_number, presence: true, format: {with: /\A0\d{9,10}\z/}

  def self.search_for(contents)
    Customer.where("first_name LIKE? OR last_name LIKE? OR first_name_kana LIKE? OR last_name_kana LIKE?", "%#{contents}%", "%#{contents}%", "%#{contents}%", "%#{contents}%")
  end
  
  def active_for_authentication?
    super && (self.is_deleted == true)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all
     @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(admin_customer_params)
      flash[:success] = "登録情報を変更しました。"
      redirect_to admin_customer_path(@customer.id)
    else
      render 'edit'
    end
  end

  def search
  end

  private

  def admin_customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<table class="table text-center">
  <thead>
    <tr>
      <th>姓</th>
      <th>名</th>
      <th>セイ</th>
      <th>メイ</th>
      <th>郵便番号</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>メールアドレス</th>
      <th>会員ステータス</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% customers.each do |customer| %>
    <tr>
      <td><%= customer.last_name %></td>
      <td><%= customer.first_name %></td>
      <td><%= customer.last_name_kana %></td>
      <td><%= customer.first_name_kana %></td>
      <td><%= customer.postal_code %></td>
      <td><%= customer.address %></td>
      <td><%= customer.telephone_number %></td>
      <td><%= customer.email %></td>
      <td>
        <% if customer.is_deleted == 1 %>
          <p>有効</p>
        <% else %>
          <p>無効</p>
        <% end %>
      </td>
      <td class="text-center">
        <p><%= link_to '会員詳細', admin_customer_path(customer.id), class: "sbtn btn-6" %></p>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/customers/edit.html.erb
<div class="container">
<h2>会員編集ページ</h2>

<% if @customer.errors.any? %>
    <div id="error_explanation">
     <ul>
       <% @customer.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
      </ul>
    </div>
<% end %>

<%= form_with model: @customer, url: admin_customer_path(@customer) ,local: true do |f| %>

  <div class="field">
    <label for="name" class="col-md-2 col-sm-2 col-xs-12">名前</label>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "col-md-2 col-sm-2 col-xs-12" %>
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "col-md-2 col-sm-2 col-xs-12" %>
  </div>

  <div class="field">
    <label for="name_kana" class="col-md-2 col-sm-2 col-xs-12">名前(カナ)</label>
    <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: "col-md-2 col-sm-2 col-xs-12" %>
    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class: "col-md-2 col-sm-2 col-xs-12" %>
  </div>

  <div class="field">
    <label for="postal_code" class="col-md-2 col-sm-2 col-xs-12">郵便番号</label>
    <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: "col-md-2 col-sm-2 col-xs-12" %>
  </div>

  <div class="field">
    <label for="address" class="col-md-2 col-sm-2 col-xs-12">住所</label>
    <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "col-md-2 col-sm-2 col-xs-12" %>
  </div>

  <div class="field">
    <label for="telephone_number" class="col-md-2 col-sm-2 col-xs-12">電話番号</label>
    <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number", class: "col-md-2 col-sm-2 col-xs-12" %>
  </div>

  <div class="field">
    <label for="email" class="col-md-2 col-sm-2 col-xs-12">メールアドレス</label>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-md-2 col-sm-2 col-xs-12" %>
  </div>

  <div class="field">
    <label for="is_deleted" class="col-md-2 col-sm-2 col-xs-12">会員ステータス</label>
    <%= f.radio_button :is_deleted, true %>
    <%= f.label :is_deleted, "有効", {value: :true, style: "display: inline-block;"} %>
    <%= f.radio_button :is_deleted, false %>
    <%= f.label :is_deleted, "退会済み", {value: :false, style: "display: inline-block;"} %>
  </div>

  <div class="actions">
    <%= f.submit "更新する", class: "sbtn btn-6 col-md-2 col-sm-2 col-xs-12" %>
  </div>
<% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h2>会員一覧</h2>

   <% if @customer.errors.any? %>
    <div id="error_explanation">
     <ul>
       <% @customer.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
      </ul>
    <div>
  <% end %>

  <div>
    <table class="table text-center">
      <thead>
        <tr>
          <th>姓</th>
          <th>名</th>
          <th>セイ</th>
          <th>メイ</th>
          <th>郵便番号</th>
          <th>住所</th>
          <th>電話番号</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td id="td-reset"><%= customer.last_name %></td>
            <td id="td-reset"><%= customer.first_name %></td>
            <td id="td-reset"><%= customer.last_name_kana %></td>
            <td id="td-reset"><%= customer.first_name_kana %></td>
            <td id="td-reset"><%= customer.postal_code %></td>
            <td id="td-reset"><%= customer.address %></td>
            <td id="td-reset"><%= customer.telephone_number %></td>
            <td id="td-reset"><%= customer.email %></td>
            <td id="td-reset">
                <% if customer.is_deleted == true %>
                  在籍
                <% else %>
                  退会済み
                <% end %>
            </td>
            <td class="text-center" id="td-reset"><%= link_to '会員詳細', admin_customer_path(customer.id), class: "sbtn btn-6" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/admin/customers/show.html.erb
  <div class="container">
    <h2>会員詳細ページ</h2>
    <div class="col-md-6 col-sm-6 col-xs-6">
      <div class="form-group row">
        <label for="name" class="col-md-4 col-sm-4 col-xs-12">姓・名</label>
        <%= @customer.last_name %>
        <%= @customer.first_name %>
      </div>
      <div class="form-group row">
        <label for="name_kana" class="col-md-4 col-sm-4 col-xs-12">セイ・メイ</label>
        <%= @customer.last_name_kana %>
        <%= @customer.first_name_kana %>
      </div>
      <div class="form-group row">
        <label for="postal_code" class="col-md-4 col-sm-4 col-xs-12">郵便番号</label>
        <%= @customer.postal_code %>
      </div>
      <div class="form-group row">
        <label for="address" class="col-md-4 col-sm-4 col-xs-12">住所</label>
        <%= @customer.address %>
      </div>
      <div class="form-group row">
        <label for="telephone_number" class="col-md-4 col-sm-4 col-xs-12">電話番号</label>
        <%= @customer.telephone_number %>
      </div>
      <div class="form-group row">
        <label for="email" class="col-md-4 col-sm-4 col-xs-12">メールアドレス</label>
        <%= @customer.email %>
      </div>
      <div class="form-group row">
        <label for="is_deleted" class="col-md-4 col-sm-4 col-xs-12">会員ステータス</label>
        <% if @customer.is_deleted == true %>
          <p>在籍</p>
        <% else %>
          <p>退会済み</p>
        <% end %>
      </div>
      <div>
        <p><%= link_to '会員情報編集', edit_admin_customer_path(@customer.id), class: "sbtn btn-6 text-center admin-mypage" %></p>
        <p><%= link_to '注文履歴一覧', admin_customer_orders_path(@customer.id), class: "sbtn btn-6 text-center admin-mypage" %></p>
      </div>
    </div>
  </div>