config/routes.rb
Rails.application.routes.draw do




  root to: 'public/homes#top'

  devise_for :admins, controllers: {
   sessions: 'admin/admins/sessions',
   passwords: 'admin/admins/passwords'
  }

  namespace :admin do
   #resources :customers, only: %i(show edit update index)
  # resources :questions, only: %i(index destroy)
  end
  devise_for :customers, controllers: {
    sessions:      'public/customers/sessions',
    passwords:     'public/customers/passwords',
    registrations: 'public/customers/registrations'
  }


  scope module: :public do
    get 'orders/thank_you' => 'orders#thank_you'
    get 'orders/confirm' => 'orders#new'
    resources :orders ,only: [:new ,:index ,:show ,:create] do
      collection do
        post :confirm
      end
    end

    resources :customers ,only: [:show,:edit,:update]
    resources :deliveries ,only: [:index, :create, :edit, :destroy, :update]
    resources :products ,only: [ :index, :show]

    get 'search' => 'products#search'
    delete '/cart_items/destroy_all'
    resources :cart_items ,only: [:index, :create, :update, :destroy]

    get '/' => 'homes#top', as: 'homes_top'
    get 'homes/about'
    get 'customers/:id/confirm' => 'customers#confirm', as: 'customers_confirm'
    patch 'customers/destroy/:id' => 'customers#destroy' , as: 'customers_destroy'
    get 'public/search' => 'searches#search', as: 'public_search'
  end


  namespace :admin do
    get '/customer/order/:id' => 'orders#customerindex',as: 'customer_orders'
    resources :orders ,only: [:show,:index,:update]
    resources :order_details ,only: [:update]
    resources :customers ,only: [:index, :show, :edit, :update]
    resources :genres ,only: [:index, :create, :edit, :update, :destroy]
    get "/genres/:id", to: "genres#edit"
    resources :products ,only: [:new, :create, :show, :index, :edit, :update, :destroy]
    root to: 'orders#index'
    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :customer_id, presence: true
  validates :name, presence: true

  validates :postcode, presence: true, format: {with: /\A\d{3}[-]?\d{4}\z/}
  validates :address, presence: true
  validates :shipping, presence: true
  validates :payment_methods, presence: true
  validates :total_payment, presence: true
  validates :status, presence: true
  validates :address_kind, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @orders = Order.order(id: :DESC)
  end
  def customerindex
    @orders = Order.where(customer_id: params[:id])
    render :index
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = "注文ステータスを変更しました。"
      if @order.status == 1
        @order_details = @order.order_details
        @order_details.each do |od|
          @order_detail = OrderDetail.find_by(id: od.id)
          @order_detail.update(order_detail1)
        end
      end
      redirect_to admin_order_path(@order)
    else
      flash[:alert]="注文ステータスの変更に失敗しました。"
      render :show
    end

  end



  def show
    @order = Order.find(params[:id])
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
  def order_detail1
    {production_status: 1}
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/create.html.erb
<h1>Public::Orders#index</h1>
<p>Find me in app/views/public/orders/index.html.erb</p>
<div class="container mt-5">
  <%= link_to 'new', new_order_path %>
	<div class="row">

		<div class="col-md-12 col-sm-12 col-xs-12">
      <h2>注文一覧<span class="small">(全<%= @orders.count %>件)</span></h2>
			<div class="row">
				<table class="table text-center">
				  <thead>
				    <th>order.id</th>
				    <th>customer_id</th>
				    <th>name</th>
				    <th>postcode</th>
				    <th>addres</th>
				    <th>shipping</th>
				    <th>payment_methods</th>
				    <th>total_payment</th>
				    <th>status</th>
				    <th>address_kind</th>
				    <th>created_at</th>
				  </thead>
				  <tbody>
  					<% @orders.each do |order| %>
    					<tr>
    					  <td><%= order.id%></td>
                <td><%= order.customer_id%></td>
                <td><%= order.name %></td>
                <td><%= order.postcode %></td>
                <td><%= order.address %></td>
                <td><%= order.shipping %></td>
                <td><%= order.payment_methods %></td>
                <td><%= order.total_payment %></td>
                <td><%= order.status %></td>
                <td><%= order.address_kind %></td>
                <td><%= order.created_at %></td>
    					</tr>

	    			<% end %>

				  </tbody>
				</table>

			</div>
		</div>
	</div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-10 col-sm-10 col-xs-10">
      <h2>注文一覧<span class="small">(全<%= @orders.count %>件)</span></h2>
			<div class="row">
				<table class="table text-center">
				  <thead class="m-2">
				    <th>購入日時</th>
				    <th>購入者</th>
				    <th>注文個数</th>
				    <th>注文ステータス</th>
				  </thead>
				  <tbody>
  					<% @orders.each do |order| %>
    					<tr>
    					  <td>
    					  	<%=link_to admin_order_path(order.id) do %>
    					  		<%= order.created_at%>
    					  	<%end%>
    					  </td>
                <td><%= order.customer.last_name %> <%= order.customer.first_name%></td>
                <td>
                	<% @sum =0 %>
                	<% order.order_details.each do |order_details| %>
                		<%@sum=@sum+ order_details.quantity%>
                	<%end%>
                	<%=@sum%>
                </td>

                <td>
    							<%if  order.status== 0 %>
										入金待ち
									<%elsif order.status == 1 %>
										入金確認
									<%elsif order.status == 2 %>
										製作中
									<%elsif order.status == 3 %>
										発送準備中
									<%elsif order.status == 4 %>
										発送済み
									<%end%>
                </td>
    					</tr>

	    			<% end %>

				  </tbody>
				</table>

			</div>
		</div>
	</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">


  <h3>注文履歴詳細</h3>
  <div class="row col-md-5 col-sm-5 col-xs-5">
    <table class="table">
      <tbody>
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order) do %>
              <%=@order.customer.last_name%> <%=@order.customer.first_name%>
            <%end%>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%=@order.created_at%></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%=@order.postcode%> <%=@order.address%></br><%@order.name%></td>
        </tr>
        <tr>
          <% if @order.payment_methods == 1 %>
            <th>支払い方法</th>
            <td>クレジットカード</td>
        　<%elsif @order.payment_methods == 0 %>
            <th>支払い方法</th>
            <td>銀行振り込み</td>
          <%end %>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <% if @order.status ==1 or @order.status==2%>
             <% if @order.status ==1 %>
               入金確認
             <% elsif @order.status == 2%>
               製作中
             <%end%>
            <%else %>
              <%= form_with model: @order ,url: admin_order_path ,local: true do |f| %>
                <%= f.select :status, [["入金待ち", 0], ["入金確認", 1], ["製作中", 2], ["発送準備中", 3], ["発送済み", 4]] %>
                <%= f.submit"変更", class: "change-btn" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="row col-md-11 col-sm-11 col-xs-11">
      <table class="table">
          <thead>
              <tr>
                  <th>商品名</th>
                  <th>単価(税込)</th>
                  <th>数量</th>
                  <th>小計</th>
                  <th>制作ステータス</th>

              </tr>
          </thead>
          <tbody>
              <%@order.order_details.each do |f|%>
                  <tr>
                    <td><%=f.product.name%></td>
                    <td><%=f.product.price%></td>
                    <td><%=f.quantity%></td>
                    <td><%=f.price%></td>
                    <td>
                      <% if f.production_status == 0 or @order.status ==4%>
                        <%if f.production_status == 0%>
                          着手不可
                        <% elsif @order.status == 4%>
                          制作完了
                        <%end%>
                      <%else%>
                        <%= form_with model: f ,url: admin_order_detail_path(f) ,local: true do |f| %>
                          <%= f.select :production_status, [["着手不可", 0], ["制作待ち", 1], ["製作中", 2], ["制作完了", 3]] %>
                          <%= f.submit"変更", class: "change-btn" %>
                        <% end %>
                      <%end%>
                    </td>
                  </tr>
              <%end%>
          </tbody>
      </table>
  </div>
</div>