config/routes.rb
Rails.application.routes.draw do




  root to: 'public/homes#top'

  devise_for :admins, controllers: {
   sessions: 'admin/admins/sessions',
   passwords: 'admin/admins/passwords'
  }

  namespace :admin do
   #resources :customers, only: %i(show edit update index)
  # resources :questions, only: %i(index destroy)
  end
  devise_for :customers, controllers: {
    sessions:      'public/customers/sessions',
    passwords:     'public/customers/passwords',
    registrations: 'public/customers/registrations'
  }


  scope module: :public do
    get 'orders/thank_you' => 'orders#thank_you'
    get 'orders/confirm' => 'orders#new'
    resources :orders ,only: [:new ,:index ,:show ,:create] do
      collection do
        post :confirm
      end
    end

    resources :customers ,only: [:show,:edit,:update]
    resources :deliveries ,only: [:index, :create, :edit, :destroy, :update]
    resources :products ,only: [ :index, :show]

    get 'search' => 'products#search'
    delete '/cart_items/destroy_all'
    resources :cart_items ,only: [:index, :create, :update, :destroy]

    get '/' => 'homes#top', as: 'homes_top'
    get 'homes/about'
    get 'customers/:id/confirm' => 'customers#confirm', as: 'customers_confirm'
    patch 'customers/destroy/:id' => 'customers#destroy' , as: 'customers_destroy'
    get 'public/search' => 'searches#search', as: 'public_search'
  end


  namespace :admin do
    get '/customer/order/:id' => 'orders#customerindex',as: 'customer_orders'
    resources :orders ,only: [:show,:index,:update]
    resources :order_details ,only: [:update]
    resources :customers ,only: [:index, :show, :edit, :update]
    resources :genres ,only: [:index, :create, :edit, :update, :destroy]
    get "/genres/:id", to: "genres#edit"
    resources :products ,only: [:new, :create, :show, :index, :edit, :update, :destroy]
    root to: 'orders#index'
    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  attachment :image

  validates :image, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true

  def add_tax_price
    (self.price * 1.10).round
  end

  def self.looks(ids)
    where("genre_id LIKE?","#{ids}")
  end

  def self.search_for(contents)
    Product.where("name LIKE?", "%#{contents}%")
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @genres = Genre.all
    @product = Product.new
  end

  def create
    @genres = Genre.all
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
      flash[:notice] = "#{@product.name}が追加されました"
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.page(params[:page])
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def update
    @genres = Genre.all
    @product = Product.find(params[:id])
    if @product.update(product_params)
       redirect_to admin_products_path
       flash[:notice] = "#{@product.name}が変更されました"
    else
       render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
    flash[:notice] = "#{@product.name}が削除されました"
  end

  private
  def product_params
    params.require(:product).permit(:image, :name, :description, :genre_id, :price, :sales_status)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_index.html.erb
<h2 class="mb-3">商品<span class="small">(全<%= products.count %>件)</span></h2>
<div class="row ml-1">
  <% products.each do |product| %>
    <div class="flex-wrap">
      <%= link_to product_path(product.id) do %>
        <%= attachment_image_tag product, :image, :fill, 180, 180, format: 'jpeg', class: "border-radius mb-2" %>
      <% end %>
      <p class="m-0"><%= link_to product.name, product_path(product) %></p>
      <p>¥<%= product.price %></p>
    </div>
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<div class="container">
  <h2 class="mt-5">商品編集</h2>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <ul>
       <% @product.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-5 mb-5">
    <%= form_with model: @product, url: admin_product_path(@product), local: true do |f| %>
      <div class="form-group row">
        <%= f.label :image, "商品画像", class: "col-sm-2" %>
        <%= f.attachment_field :image, class: "col-sm-4 p-0" %>
      </div>
      <div class="form-group row">
        <%= f.label :name, "商品名", class: "col-sm-2" %>
        <%= f.text_field :name, class: "col-sm-3" %>
      </div>
      <div class="form-group row">
        <%= f.label :description, "商品説明", class: "col-sm-2" %>
        <%= f.text_area :description, class: "col-sm-3" %>
      </div>
      <div class="form-group row">
        <%= f.label :genre_id, "ジャンル", class: "col-sm-2" %>
        <%= f.collection_select(:genre_id, @genres, :id, :name) %>
      </div>
      <div class="form-group row">
        <%= f.label :price, "税抜価格", class: "col-sm-2" %>
        <%= f.text_field :price, class: "col-sm-3" %>円
      </div>
      <div class="form-group row">
        <%= f.label :sales_status, "販売ステータス", class: "col-sm-2" %>
        <%= f.radio_button :sales_status, false, class: 'mt-1' %>
        <%= f.label :sales_status, '販売中', value: :false %>
        <%= f.radio_button :sales_status, true, class: 'mt-1 ml-3' %>
        <%= f.label :sales_status, '販売停止', value: :true %>
      </div>
      <div class="form-group row ">
        <%= f.submit "変更を保存", class: "sbtn btn-6  ml-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between mt-3">
    <h2>商品一覧</h2>
    <%= link_to "商品を追加する", new_admin_product_path, class: "sbtn btn-2 m-0 font-weight-bold text-center add-btn"%>
  </div>

    <table class="table">
      <thead class="thead">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= link_to product.name, admin_product_path(product) %></td>
          <td><%= product.price %></td>
          <td><%= product.genre.name %></td>
          <td>
            <% if product.sales_status == false  %>
              <p class="text-success m-0">販売中</p>
            <% else %>
              <p class="text-secondary m-0">販売停止中</p>
            <% end %>
          </td>
          <td>
              <%= link_to"×", admin_product_path(product), class: "cart-delete-btn", method: :delete, data: {confirm: "本当に消しますか？"} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <%= paginate @products %>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <h2>商品新規登録</h2>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <ul>
       <% @product.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form_with model: @product, url: "/admin/products", local: true do |f| %>
      <div class="form-group row">
        <%= f.label :image, "商品画像", class: "col-sm-2" %>
        <%= f.attachment_field :image, class: "col-sm-4 p-0" %>
      </div>
      <div class="form-group row">
        <%= f.label :name, "商品名", class: "col-sm-2" %>
        <%= f.text_field :name, class: "col-sm-3" %>
      </div>
      <div class="form-group row">
        <%= f.label :description, "商品説明", class: "col-sm-2" %>
        <%= f.text_area :description, class: "col-sm-3" %>
      </div>
      <div class="form-group row">
        <%= f.label :genre_id, "ジャンル", class: "col-sm-2" %>
        <%= f.collection_select(:genre_id, @genres, :id, :name) %>
      </div>
      <div class="form-group row">
        <%= f.label :price, "税抜価格", class: "col-sm-2" %>
        <%= f.text_field :price, class: "col-sm-3" %>円
      </div>
      <div class="form-group row radio-button">
        <%= f.label :sales_status, "販売ステータス", class: "col-sm-2" %>
        <%= f.radio_button :sales_status, false, class: 'mt-1' %>
        <%= f.label :sales_status, '販売中', value: :false %>
        <%= f.radio_button :sales_status, true, class: 'mt-1 ml-3' %>
        <%= f.label :sales_status, '販売停止', value: :true %>
      </div>
      <div class="form-group row">
        <%= f.submit "新規登録", class: "sbtn btn-6 m-0 ml-3 py-2" %>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <h2>商品詳細</h2>

  <div class="row">
  <div class="d-flex">
    <div class="flex-wrap mr-5">
      <%= attachment_image_tag @product, :image, :fill, 280, 220, format: 'jpeg', class: "border-radius" %>
    </div>
  <div class="flex-wrap">
    <div>
      <label class="field-size">商品名</label>
      <%= @product.name %>
    </div>
    <div>
      <label class="field-size">商品説明</label>
      <%= @product.description %>
    </div>
    <div>
      <label class="field-size">ジャンル</label>
       <%= @product.genre.name %>
    </div>
    <div>
      <label class="field-size">税込価格(税抜価格)</label>
      <%= @product.price %>円
    </div>
    <div>
      <label class="field-size">販売ステータス</label>
      <% if @product.sales_status == false  %>
        <span class="text-success">販売中</span>
      <% else %>
        <span class="text-secondary">販売停止中</span>
      <% end %>
    </div>
    <div class="form-group row text-center mt-4">
      <%= link_to"編集する", edit_admin_product_path(@product), class: "sbtn btn-6 m-0 ml-3" %>
    </div>
  </div>
</div>