config/routes.rb
Rails.application.routes.draw do




  root to: 'public/homes#top'

  devise_for :admins, controllers: {
   sessions: 'admin/admins/sessions',
   passwords: 'admin/admins/passwords'
  }

  namespace :admin do
   #resources :customers, only: %i(show edit update index)
  # resources :questions, only: %i(index destroy)
  end
  devise_for :customers, controllers: {
    sessions:      'public/customers/sessions',
    passwords:     'public/customers/passwords',
    registrations: 'public/customers/registrations'
  }


  scope module: :public do
    get 'orders/thank_you' => 'orders#thank_you'
    get 'orders/confirm' => 'orders#new'
    resources :orders ,only: [:new ,:index ,:show ,:create] do
      collection do
        post :confirm
      end
    end

    resources :customers ,only: [:show,:edit,:update]
    resources :deliveries ,only: [:index, :create, :edit, :destroy, :update]
    resources :products ,only: [ :index, :show]

    get 'search' => 'products#search'
    delete '/cart_items/destroy_all'
    resources :cart_items ,only: [:index, :create, :update, :destroy]

    get '/' => 'homes#top', as: 'homes_top'
    get 'homes/about'
    get 'customers/:id/confirm' => 'customers#confirm', as: 'customers_confirm'
    patch 'customers/destroy/:id' => 'customers#destroy' , as: 'customers_destroy'
    get 'public/search' => 'searches#search', as: 'public_search'
  end


  namespace :admin do
    get '/customer/order/:id' => 'orders#customerindex',as: 'customer_orders'
    resources :orders ,only: [:show,:index,:update]
    resources :order_details ,only: [:update]
    resources :customers ,only: [:index, :show, :edit, :update]
    resources :genres ,only: [:index, :create, :edit, :update, :destroy]
    get "/genres/:id", to: "genres#edit"
    resources :products ,only: [:new, :create, :show, :index, :edit, :update, :destroy]
    root to: 'orders#index'
    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :quantity, presence: true
  validates :product_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ぁ-んァ-ン]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ぁ-んァ-ン]+\z/}
  validates :postal_code, presence: true, format: {with: /\A\d{3}[-]?\d{4}\z/}
  validates :address, presence: true
  validates :telephone_number, presence: true, format: {with: /\A0\d{9,10}\z/}

  def self.search_for(contents)
    Customer.where("first_name LIKE? OR last_name LIKE? OR first_name_kana LIKE? OR last_name_kana LIKE?", "%#{contents}%", "%#{contents}%", "%#{contents}%", "%#{contents}%")
  end
  
  def active_for_authentication?
    super && (self.is_deleted == true)
  end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer


  # VALID_POSTAL_CODE_REGEX = /\A\d{3}[-]?\d{4}\z/

  validates :name, presence: true
  validates :postcode, presence: true, format: { with: /\A\d{3}[-]?\d{4}\z/ }
  validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :customer_id, presence: true
  validates :name, presence: true

  validates :postcode, presence: true, format: {with: /\A\d{3}[-]?\d{4}\z/}
  validates :address, presence: true
  validates :shipping, presence: true
  validates :payment_methods, presence: true
  validates :total_payment, presence: true
  validates :status, presence: true
  validates :address_kind, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :product_id, presence: true
  validates :order_id, presence: true
  validates :quantity, presence: true
  validates :price, presence: true
  validates :production_status, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  attachment :image

  validates :image, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true

  def add_tax_price
    (self.price * 1.10).round
  end

  def self.looks(ids)
    where("genre_id LIKE?","#{ids}")
  end

  def self.search_for(contents)
    Product.where("name LIKE?", "%#{contents}%")
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resourse)
    case resourse
    when Admin
      admin_root_path
    when Customer
      customer_path(current_customer)
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>
      <div class ="container">
        <div>
        <div>
          <h1>
            <%= link_to "Nakopa", root_path, class: "header-logo" %>
          </h1>
        </div>
        <div>
        <nav class="navbar navbar-expand-lg navbar-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <% if customer_signed_in? %>
                <li class="nav-item text-center mr-3">
                  <%= link_to 'マイページ', customer_path(current_customer), class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to '商品一覧', products_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to 'カート', cart_items_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center">
                  <%= link_to "ログアウト", destroy_customer_session_path, class: "nav-link", method: :delete %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item text-center mr-3">
                  <%= link_to '商品一覧', admin_products_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to '会員一覧', admin_customers_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to '注文履歴一覧', admin_orders_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to 'ジャンル一覧', admin_genres_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item text-center mr-3">
                  <%= link_to 'About', homes_about_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to '商品一覧', products_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to '新規登録', new_customer_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to 'ログイン', new_customer_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item text-center mr-3">
                  <%= link_to '管理者ログイン', new_admin_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
             <%= render 'layouts/search' %>
          </div>
        </nav>
        </div>
        </div>
      </div>
    </header>

app/views/layouts/_search.html.erb
<% if customer_signed_in? %>
  <div class='my-lg-0'>
    <%= form_with url: public_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :content,class: "form-control mr-sm-2" %>
      <%= f.submit '検索', class: "sbtn btn-6 my-2" %>
    <% end %>
  </div>
<% elsif admin_signed_in? %>
  <div class='my-lg-0'>
    <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :content,class: "form-control mr-sm-2" %>
      <%= f.select :model, options_for_select({ "Customer" => "customer", "Product" => "product" }), class: "dropdown-item" %>
      <%= f.submit '検索', class: "sbtn btn-6 my-2" %>
    <% end %>
  </div>
<% else %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "UTF-8"/>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js" charset="UTF-8"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
    <div class="container sukima">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key} alert-view") %>
      <% end %>
    </div>
      <%= yield %>
    </main>
    <footer class="text-center">
      <p>©︎なこぱ-DMMwebcamp</p>
    </footer>
  </body>
</html>